server:
  port: 8081
spring:
  application:
    name: auth-service
  config:
    import: "optional:classpath:/"
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  file:
    name: /logs/auth-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
