server:
  port: 8087

spring:
  application:
    name: notification-service
  config:
    import: "optional:classpath:/"
    
  rabbitmq:
   host: rabbitmq
   port: 5672
   username: guest
   password: guest
   queue: order.queue
rabbitmq:
 order:
    queue: order.queue
    exchange: order.exchange
    routing-key: order.created.key
        
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework: TRACE
