server:
  port: 8087

spring:
  application:
    name: notification-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    queue: order.queue
    
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    org.springframework: TRACE
