global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'order-service:8082'
          - 'notification-service:8087'
          - 'auth-service:8081'
