server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: "optional:classpath:/"
  rabbitmq:
    host: rabbitmq  # or rabbitmq (if running via Docker Compose)
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
rabbitmq:
  order:
    queue: order.queue
    exchange: order.exchange
    routing-key: order.created.key
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/  # optional, if you're skipping Eureka during dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method