server:
  port: 8086

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://inventory-db:5432/inventorydb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
