spring:
  application:
    name: cart-service  # Or cart-service, etc.
  config:
    import: "optional:classpath:/"
  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084
flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/cartdb
  user: postgres
  password: password
  
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: /logs/cart-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.flywaydb.core: DEBUG
    com.fooddelivery.*: TRACE

