server:
  port: 8084

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://cart-db:5432/cartdb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
