spring:
  application:
    name: cart-service  # Or cart-service, etc.
  config:
    import: optional:configserver:http://config-server:8888
server:
  port: 8084

logging:
  file:
    name: /logs/cart-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

