server:
  port: 8888
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samangal/food-config-repo
          clone-on-start: true

logging:
  file:
    name: /logs/config-server.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
